apiVersion: crd.antrea.io/v1beta1
kind: Egress
metadata:
  name: egress-config
spec:
  appliedTo:
    namespaceSelector:
      matchLabels:
        ext-net-03: egress-ip-03
  externalIPPool: external-ippool-egress-003
