apiVersion: crd.antrea.io/v1beta1
kind: Egress
metadata:
  name: egress-config
spec:
  appliedTo:
    namespaceSelector:
      matchLabels:
        ext-net-02: egress-ip-02
  externalIPPool: external-ippool-egress-002
